name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test
        run: cargo test --all -- --nocapture

  fmt:
    name: fmt Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt

      - name: Run fmt
        run: cargo fmt --all -- --check

  clipy:
    name: clippy Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy

      - name: Run clipy
        run: cargo clippy --all-targets --all-features -- -D warnings
